In [37]:
# https://algotrading101.com/learn/yahoo-finance-api-guide/
# http://theautomatic.net/yahoo_fin-documentation/
# yahoo_fin

from yahoo_fin.stock_info import get_data, get_quote_table, get_stats, get_quote_data, get_market_status, get_quote_data
import csv

In [26]:
# Load CSV data
#  SSE Composite Index (000001.SS), Shenzhen Component (399001.SZ)
ticker_list = ['000001.SS', '399001.SZ']

sse_csv = csv.reader(open('./data/SSE_A-shares Main Board.csv', 'r', encoding='utf-8'))
count = -1
for row in sse_csv:
    count += 1
    if count == 0:
        continue
    if count > 5:
        break
    ticker_list.append(row[5])

szse_csv = csv.reader(open('./data/SZSE_A-shares Main Board.csv', 'r', encoding='utf-8'))
count = -1
for row in szse_csv:
    count += 1
    if count == 0:
        continue
    if count > 5:
        break
    ticker_list.append(row[19])

print(ticker_list)
print(len(ticker_list))

['000001.SS', '399001.SZ', '600000.SS', '600004.SS', '600006.SS', '600007.SS', '600008.SS', '000001.SZ', '000002.SZ', '000004.SZ', '000005.SZ', '000006.SZ']
12

In [27]:
historical_datas = {}
for ticker in ticker_list:
    historical_datas[ticker] = get_data(ticker, start_date = None, end_date = None, index_as_date = False, interval = "1d")

In [28]:
historical_datas['600000.SS']

,date,open,high,low,close,adjclose,volume,ticker
0,1999-11-10,3.439483,3.474461,3.148002,3.235446,2.068513,1.493105e+09,600000.SS
1,1999-11-11,3.215625,3.308900,3.209796,3.230782,2.065531,2.521899e+08,600000.SS
2,1999-11-12,3.248271,3.299572,3.237778,3.270424,2.090875,1.287213e+08,600000.SS
3,1999-11-15,3.287913,3.293743,3.229617,3.235446,2.068513,1.022455e+08,600000.SS
4,1999-11-16,3.250603,3.261097,3.087373,3.095535,1.979064,1.991816e+08,600000.SS
...,...,...,...,...,...,...,...,...
5295,2021-03-12,10.890000,11.030000,10.820000,10.900000,10.900000,7.923563e+07,600000.SS
5296,2021-03-15,10.880000,11.240000,10.880000,11.120000,11.120000,1.135244e+08,600000.SS
5297,2021-03-16,11.080000,11.240000,11.010000,11.110000,11.110000,6.550226e+07,600000.SS
5298,2021-03-17,11.100000,11.120000,10.890000,10.920000,10.920000,5.782185e+07,600000.SS
5299,2021-03-18,10.970000,11.050000,10.900000,11.030000,11.030000,5.094355e+07,600000.SS

In [29]:
for ticker in historical_datas:
    historical_datas[ticker].to_csv('./output/' + ticker + '.csv')

In [30]:
quote_table = get_quote_table('600000.SS', dict_result=False)
quote_table

                   attribute                        value
0              1y Target Est                        11.58
1              52 Week Range                 9.22 - 12.69
2                        Ask                    11.04 x 0
3                Avg. Volume                   79075566.0
4          Beta (5Y Monthly)                         0.44
5                        Bid                    11.03 x 0
6                Day's Range                10.90 - 11.05
7                  EPS (TTM)                         1.64
8              Earnings Date  Apr 30, 2021 - May 04, 2021
9           Ex-Dividend Date                 Jul 23, 2020
10  Forward Dividend & Yield                 0.60 (5.49%)
11                Market Cap                     323.754B
12                      Open                        10.97
13            PE Ratio (TTM)                         6.71
14            Previous Close                        10.92
15               Quote Price                        11.03
16                    Volume                   50943550.0

In [41]:
get_stats('600000.SS')

                           Attribute         Value
0                  Beta (5Y Monthly)          0.44
1                   52-Week Change 3         9.86%
2            S&P500 52-Week Change 3        65.26%
3                     52 Week High 3         12.69
4                      52 Week Low 3          9.22
5            50-Day Moving Average 3         10.64
6           200-Day Moving Average 3          9.95
7                Avg Vol (3 month) 3        79.08M
8                 Avg Vol (10 day) 3        75.89M
9               Shares Outstanding 5        29.35B
10                             Float         9.53B
11              % Held by Insiders 1        50.74%
12          % Held by Institutions 1        22.50%
13                    Shares Short 4           NaN
14                     Short Ratio 4           NaN
15                Short % of Float 4           NaN
16   Short % of Shares Outstanding 4           NaN
17     Shares Short (prior month ) 4           NaN
18    Forward Annual Dividend Rate 4           0.6
19   Forward Annual Dividend Yield 4         5.49%
20   Trailing Annual Dividend Rate 3          0.60
21  Trailing Annual Dividend Yield 3         5.49%
22   5 Year Average Dividend Yield 4          2.68
23                    Payout Ratio 4        36.81%
24                   Dividend Date 3           NaN
25                Ex-Dividend Date 4  Jul 23, 2020
26               Last Split Factor 2         13:10
27                 Last Split Date 3  May 25, 2017
28                  Fiscal Year Ends  Dec 31, 2019
29         Most Recent Quarter (mrq)  Sep 30, 2020
30                     Profit Margin        50.08%
31            Operating Margin (ttm)        56.99%
32            Return on Assets (ttm)         0.77%
33            Return on Equity (ttm)         9.90%
34                     Revenue (ttm)       110.42B
35           Revenue Per Share (ttm)          3.67
36    Quarterly Revenue Growth (yoy)        -2.30%
37                Gross Profit (ttm)        115.5B
38                            EBITDA           NaN
39    Net Income Avi to Common (ttm)        53.58B
40                 Diluted EPS (ttm)          1.64
41   Quarterly Earnings Growth (yoy)        -2.80%
42                  Total Cash (mrq)         1.13T
43        Total Cash Per Share (mrq)         38.35
44                  Total Debt (mrq)         1.76T
45           Total Debt/Equity (mrq)           NaN
46               Current Ratio (mrq)           NaN
47        Book Value Per Share (mrq)         18.50
48         Operating Cash Flow (ttm)       208.91B
49      Levered Free Cash Flow (ttm)           NaN

In [42]:
get_quote_data('600000.SS')

{'language': 'en-US',
 'region': 'US',
 'quoteType': 'EQUITY',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': False,
 'currency': 'CNY',
 'firstTradeDateMilliseconds': 942197400000,
 'priceHint': 2,
 'earningsTimestamp': 1604141940,
 'earningsTimestampStart': 1619780340,
 'earningsTimestampEnd': 1620129600,
 'trailingAnnualDividendRate': 0.6,
 'trailingPE': 6.7133293,
 'trailingAnnualDividendYield': 0.054945055,
 'epsTrailingTwelveMonths': 1.643,
 'epsForward': 1.97,
 'sharesOutstanding': 29352099840,
 'bookValue': 18.501,
 'fiftyDayAverage': 10.636111,
 'fiftyDayAverageChange': 0.39388847,
 'fiftyDayAverageChangePercent': 0.03703313,
 'twoHundredDayAverage': 9.950419,
 'twoHundredDayAverageChange': 1.0795803,
 'twoHundredDayAverageChangePercent': 0.10849596,
 'marketCap': 323753639936,
 'tradeable': False,
 'forwardPE': 5.5989847,
 'priceToBook': 0.596184,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'exchange': 'SHH',
 'shortName': 'SHANGHAI PUDONG DEVELOPMENT BAN',
 'longName': 'Shanghai Pudong Development Bank Co., Ltd.',
 'messageBoardId': 'finmb_5436383',
 'exchangeTimezoneName': 'Asia/Shanghai',
 'exchangeTimezoneShortName': 'CST',
 'gmtOffSetMilliseconds': 28800000,
 'market': 'cn_market',
 'esgPopulated': False,
 'marketState': 'REGULAR',
 'regularMarketChange': 0.10999966,
 'regularMarketChangePercent': 1.0073229,
 'regularMarketTime': 1616050805,
 'regularMarketPrice': 11.03,
 'regularMarketDayHigh': 11.05,
 'regularMarketDayRange': '10.9 - 11.05',
 'regularMarketDayLow': 10.9,
 'regularMarketVolume': 50943550,
 'regularMarketPreviousClose': 10.92,
 'bid': 11.03,
 'ask': 11.04,
 'bidSize': 0,
 'askSize': 0,
 'fullExchangeName': 'Shanghai',
 'financialCurrency': 'CNY',
 'regularMarketOpen': 10.97,
 'averageDailyVolume3Month': 79075566,
 'averageDailyVolume10Day': 75893808,
 'fiftyTwoWeekLowChange': 1.8099995,
 'fiftyTwoWeekLowChangePercent': 0.1963123,
 'fiftyTwoWeekRange': '9.22 - 12.69',
 'fiftyTwoWeekHighChange': -1.6599998,
 'fiftyTwoWeekHighChangePercent': -0.13081166,
 'fiftyTwoWeekLow': 9.22,
 'fiftyTwoWeekHigh': 12.69,
 'symbol': '600000.SS'}

In [43]:
get_market_status()

'POSTPOST'